#!/bin/bash

helm install social-network ./socialnetwork/ -n social-network --set global.mongodb.sharding.enabled=true,global.mongodb.standalone.enabled=false,global.redis.cluster.enabled=true,global.redis.standalone.enabled=false,global.memcached.cluster.enabled=true,global.memcached.standalone.enabled=false --timeout 10m0s &

